import { NextRequest, NextResponse } from "next/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { createClient } from "@/lib/supabase/server";

export async function POST(req: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

        const { content, platform } = await req.json();
        if (!content) return NextResponse.json({ error: "No content provided" }, { status: 400 });

        const apiKey = process.env.GEMINI_API_KEY;
        if (!apiKey) {
            return NextResponse.json({ error: "GEMINI_API_KEY not set" }, { status: 500 });
        }

        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

        // Create a prompt that asks for a high-quality SVG infographic
        const prompt = `
            You are a world-class graphic designer specializing in professional SaaS/Startup infographics.
            Generate a single, complete, beautiful SVG code for a social media card based on this content:
            "${content.substring(0, 500)}"

            DESIGN REQUIREMENTS:
            - Aspect Ratio: 1200x630 (Social Media Card).
            - Palette: Professional dark theme with emerald or blue accents.
            - Background: A subtle grid pattern (emerald/green lines on dark background).
            - Typography: Use standard sans-serif fonts.
            - Layout: Left side has a large conceptual icon (generated using SVG shapes), right side has a bold title and 3 bullet points.
            - Footer: Small "Generated by Spinner" branding.
            - Style: High-quality vector look, clean lines, professional spacing.

            RESULT: Return ONLY the SVG code starting with <svg and ending with </svg>. Do not wrap in markdown code blocks. NO TEXT EXPLANATION.
        `;

        const result = await model.generateContent(prompt);
        let svgCode = result.response.text().trim();

        // Clean up any markdown wrapping if the AI included it despite instructions
        svgCode = svgCode.replace(/^```svg\s*/i, "").replace(/^```html\s*/i, "").replace(/^```\s*/i, "").replace(/```\s*$/i, "");

        // Convert to data URL for easy consumption by <img> tags or direct rendering
        const base64Svg = Buffer.from(svgCode).toString('base64');
        const dataUrl = `data:image/svg+xml;base64,${base64Svg}`;

        return NextResponse.json({
            success: true,
            imageUrl: dataUrl, // We call it imageUrl to keep the frontend contract simple
            svgContent: svgCode
        });

    } catch (error: any) {
        console.error("SVG generation error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
