import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import { getOpenAI, withRetry } from "@/lib/ai-utils";

export async function POST(req: NextRequest) {
    try {
        const supabase = await createClient();
        const { data: { user } } = await supabase.auth.getUser();
        if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

        const { content, platform } = await req.json();
        if (!content) return NextResponse.json({ error: "No content provided" }, { status: 400 });
        const openai = getOpenAI();

        const designPromptGen = await withRetry(() => openai.chat.completions.create({
            model: "gpt-4o",
            messages: [
                { role: "system", content: "You are a senior creative director who creates professional infographics." },
                {
                    role: "user", content: `
                    Convert this social media content into a highly detailed infographic design prompt.
                    The infographic must follow modern SaaS design standards (Stripe, Linear, Notion style).
                    
                    CONTENT: "${content.substring(0, 500)}"
                    PLATFORM: ${platform}

                    DESIGN REQUIREMENTS:
                    - Infographic must look like it was designed by a professional designer, not AI-generated art.
                    - Define: Layout grid, Section hierarchy, Visual flow, Icon style, Color palette (emerald/dark theme), Typography, Spacing.
                    - Structure: Top header (Hook), Middle information blocks (Key Points), Bottom takeaway (Insight).
                    
                    RESULT: Return ONLY the infographic design prompt text. Do not wrap in codes. No conversational filler.
                ` }
            ],
            temperature: 0.7,
        }));

        const designPrompt = designPromptGen.choices[0].message.content || "";

        // STAGE 2: DESIGN PROMPT -> SVG EXECUTION (Senior Graphic Designer Persona)
        const svgGenPrompt = `
            You are a senior graphic designer specializing in professional SVG infographics.
            Execute the following design prompt into a single, complete, beautiful SVG code.
            
            DESIGN PROMPT: "${designPrompt}"

            TECHNICAL RULES:
            - Canvas Size: 1200x630.
            - Output: Pure SVG code. No markdown code blocks. No explanations.
            - Branding: Include a small "Generated by Spinner" text in the bottom right corner.
            - Styling: Use clear geometric shapes, thin line icons, and a subtle tech grid background.
            - Anti-AI Look: Ensure the layout is perfectly aligned and minimalist. No messy clutter.

            RESULT: Return ONLY the raw <svg> code.
        `;

        const result = await withRetry(() => openai.chat.completions.create({
            model: "gpt-4o",
            messages: [
                { role: "system", content: "You are a senior graphic designer specializing in professional SVG infographics." },
                { role: "user", content: svgGenPrompt }
            ],
            temperature: 0.2,
        }));

        let svgCode = result.choices[0].message.content || "";

        // Clean up any markdown wrapping if the AI included it despite instructions
        svgCode = svgCode.replace(/^```svg\s*/i, "").replace(/^```html\s*/i, "").replace(/^```\s*/i, "").replace(/```\s*$/i, "");

        // Convert to data URL for easy consumption by <img> tags or direct rendering
        const base64Svg = Buffer.from(svgCode).toString('base64');
        const dataUrl = `data:image/svg+xml;base64,${base64Svg}`;

        return NextResponse.json({
            success: true,
            imageUrl: dataUrl, // We call it imageUrl to keep the frontend contract simple
            svgContent: svgCode
        });

    } catch (error: any) {
        console.error("SVG generation error:", error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
